### ISSUE TITLE
batch_sign: Error: hash needs to be scanned first before submitting for signing

### ISSUE THREAD

**Issue by dmitry-kosar** [SSLcom/esigner-codesign#10]
I'm getting the following error when signing `.exe` files using batch_sign `Error: hash needs to be scanned first before submitting for signing: <hash_value>`.  There are no mentions of such an error in the documentation. 

What does this error mean?
Do I need to do some extra steps to prepare file before calling batch_sign? Or there can be an issue with the file itself?

```yml
- name: Sign files with with CodeSignTool
  uses: sslcom/esigner-codesign@develop
  with:
    command: batch_sign
    username: <username>
    password: <password>
    credential_id: <cred_id_guid>
    totp_secret: <totp_secret>
    dir_path: files-to-sign
    output_path: output
    malware_block: false
    environment_name: PROD
```
