### ISSUE TITLE
Workflow Failing due to authorization grant

### ISSUE THREAD

**Issue by cameronjeffords** [SSLcom/esigner-codesign#18]
Hello. Recently my workflow runs started failing, and I'm not really sure how to troubleshoot. This is the error I'm getting in the logs:
```Error: The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.```

I haven't changed anything with the parameters (was previously succeeding), and additionally everything seems to be up-to-date and valid on SSL.com. Do you have any troubleshooting recommendations?

Here's my workflow step:
```
- name: Sign Artifact with CodeSignTool
        if: matrix.os == 'windows-latest'
        uses: sslcom/esigner-codesign@develop
        with:
          command: sign
          username: ${{secrets.ES_USERNAME}}
          password: "${{secrets.ES_PASSWORD}}"
          credential_id: ${{secrets.CREDENTIAL_ID}}
          totp_secret: ${{secrets.ES_TOTP_SECRET}}
          file_path: ${GITHUB_WORKSPACE}/out/...
          malware_block: false
          override: true
          clean_logs: true
```
