### ISSUE TITLE
The system cannot find the file specified.

### ISSUE THREAD

**Issue by cmoody** [SSLcom/esigner-codesign#21]
I am building an Electron app. I have a github workflow that works to build apps. I am now trying to add in the code signing step. Everything looks correct, including the outputs for where files are. However once it gets to the point to run `CodeSignTool.bat` it fails. Im hoping I am just overlooking a simple path or name.

Github Workflow
```
name: Build/release Electron app

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: build-linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux

      - name: build-mac
        if: matrix.os == 'macos-latest'
        run: npm run build:mac

      - name: build-win
        if: matrix.os == 'windows-latest'
        run: npm run build:win

      - name: Sign Artifact with CodeSignTool
        if: matrix.os == 'windows-latest'
        uses: sslcom/esigner-codesign@develop
        with:
          # Sign and timestamp code object.
          command: sign
          # SSL.com account username
          username: ${{ secrets.ES_USERNAME }}
          # SSL.com account password.
          password: ${{ secrets.ES_PASSWORD }}
          # Credential ID for signing certificate.
          # credential_id: ${{ secrets.CREDENTIAL_ID }}
          # OAuth TOTP Secret (https://www.ssl.com/how-to/automate-esigner-ev-code-signing)
          # totp_secret: ${{ secrets.ES_TOTP_SECRET }}
          # Path of code object to be signed. (DLL, JAR, EXE, MSI files vb... )
          # ${name}-${version}-setup.${ext}
          file_path: ${{ github.workspace }}/dist/civitai-link-1.10.6-setup.exe
          # Directory where signed code object(s) will be written.
          output_path: ${{ github.workspace }}/dist/
          # Scan code before sign
          malware_block: false
          # Environment Name, For Production 'PROD' or For Staging 'TEST'
          environment_name: PROD

      - name: release
        uses: softprops/action-gh-release@v1
        if: always()
        with:
          draft: true
          files: |
            dist/*.exe
            dist/*.zip
            dist/*.dmg
            dist/*.AppImage
            dist/*.snap
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/*.yml
            dist/*.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

```

Sign Artifact with CodeSignTool
```
Run sslcom/esigner-codesign@develop
  with:
    command: sign
    username: ***
    password: ***
    file_path: D:\a\civitai-link-desktop\civitai-link-desktop/dist/civitai-link-1.10.6-setup.exe
    output_path: D:\a\civitai-link-desktop\civitai-link-desktop/dist/
    malware_block: false
    environment_name: PROD
    clean_logs: false
    jvm_max_memory: 10[2](https://github.com/civitai/civitai-link-desktop/actions/runs/8301240635/job/22720926021#step:9:2)4M
  
CodeSignTool output path D:\a\civitai-link-desktop\civitai-link-desktop\dist\ already exist
Input Commands: sign -username="***" -password="***" -input_file_path="D:\a\civitai-link-desktop\civitai-link-desktop\dist\civitai-link-1.10.6-setup.exe" -output_dir_path=D:\a\civitai-link-desktop\civitai-link-desktop\dist\ -malware_block=false
Created CodeSignTool base path D:\a\civitai-link-desktop\civitai-link-desktop\codesign
Downloading CodeSignTool from https://github.com/SSLcom/CodeSignTool/releases/download/v1.[3](https://github.com/civitai/civitai-link-desktop/actions/runs/8301240635/job/22720926021#step:9:3).0/CodeSignTool-v1.3.0-windows.zip
"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.ZipFile } catch { } ; try { [System.IO.Compression.ZipFile]::ExtractToDirectory('D:\a\_temp\da223500-226c-[4](https://github.com/civitai/civitai-link-desktop/actions/runs/8301240635/job/22720926021#step:9:4)ed[5](https://github.com/civitai/civitai-link-desktop/actions/runs/8301240635/job/22720926021#step:9:5)-a283-c5[6](https://github.com/civitai/civitai-link-desktop/actions/runs/8301240635/job/22720926021#step:9:6)b412dfbc2', 'D:\a\civitai-link-desktop\civitai-link-desktop\codesign\CodeSignTool-v1.3.0', $true) } catch { if (($_.Exception.GetType().FullName -eq 'System.Management.Automation.MethodException') -or ($_.Exception.GetType().FullName -eq 'System.Management.Automation.RuntimeException') ){ Expand-Archive -LiteralPath 'D:\a\_temp\da223500-226c-4ed5-a283-c56b412dfbc2' -DestinationPath 'D:\a\civitai-link-desktop\civitai-link-desktop\codesign\CodeSignTool-v1.3.0' -Force } else { throw $_ } } ;"
Extract CodeSignTool from download path D:\a\_temp\da223500-226c-4ed5-a283-c56b412dfbc2 to D:\a\civitai-link-desktop\civitai-link-desktop\codesign
Archive name: CodeSignTool-v1.3.0, D:\a\civitai-link-desktop\civitai-link-desktop\codesign\CodeSignTool-v1.3.0
Write CodeSignTool config file CLIENT_ID=kaXTRACNijSWsFdRKg_KAfD3fqrBlzMbWs6TwWHwAn8
OAUTH2_ENDPOINT=https://login.ssl.com/oauth2/token
CSC_API_ENDPOINT=https://cs.ssl.com
TSA_URL=http://ts.ssl.com
TSA_LEGACY_URL=http://ts.ssl.com/legacy to D:\a\civitai-link-desktop\civitai-link-desktop\codesign\CodeSignTool-v1.3.0\conf\code_sign_tool.properties
Set CODE_SIGN_TOOL_PATH env variable: D:\a\civitai-link-desktop\civitai-link-desktop\codesign\CodeSignTool-v1.3.0
Exec Cmd Content: @echo OFF

set code_sign_tool_path=%CODE_SIGN_TOOL_PATH%

if defined code_sign_tool_path (
%code_sign_tool_path%\jdk-11.0.2\bin\java -Xmx1024M -jar %code_sign_tool_path%\jar\code_sign_tool-1.3.0.jar %*
) else (
.\jdk-11.0.2\bin\java -Xmx1024M -jar .\jar\code_sign_tool-1.3.0.jar %*
)
Shell Cmd: cmd.exe -/c
Exec Cmd : D:\a\civitai-link-desktop\civitai-link-desktop\codesign\CodeSignTool-v1.3.0\CodeSignTool.bat
CodeSigner Command: cmd.exe -/c D:\a\civitai-link-desktop\civitai-link-desktop\codesign\CodeSignTool-v1.3.0\CodeSignTool.bat sign -username="***" -password="***" -input_file_path="D:\a\civitai-link-desktop\civitai-link-desktop\dist\civitai-link-1.10.6-setup.exe" -output_dir_path=D:\a\civitai-link-desktop\civitai-link-desktop\dist\ -malware_block=false
JDK home: C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\8.0.402-6\x64
JDK version: 0
Trying to resolve the latest version from remote
Resolved latest version as 11.0.22.[7](https://github.com/civitai/civitai-link-desktop/actions/runs/8301240635/job/22720926021#step:9:7).1
Trying to download...
Downloading Java 11.0.22.7.1 (Corretto) from https://corretto.aws/downloads/resources/11.0.22.7.1/amazon-corretto-11.0.22.7.1-windows-x64-jdk.zip ...
Extracting Java archive...
"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.ZipFile } catch { } ; try { [System.IO.Compression.ZipFile]::ExtractToDirectory('D:\a\_temp\b6072de4-d5f5-4966-[8](https://github.com/civitai/civitai-link-desktop/actions/runs/8301240635/job/22720926021#step:9:8)b1[9](https://github.com/civitai/civitai-link-desktop/actions/runs/8301240635/job/22720926021#step:9:9)-a3537892fec5', 'D:\a\_temp\c889d0c1-2d0f-4839-9cdd-068b563daa72', $true) } catch { if (($_.Exception.GetType().FullName -eq 'System.Management.Automation.MethodException') -or ($_.Exception.GetType().FullName -eq 'System.Management.Automation.RuntimeException') ){ Expand-Archive -LiteralPath 'D:\a\_temp\b6072de4-d5f5-4966-8b19-a3537892fec5' -DestinationPath 'D:\a\_temp\c889d0c1-2d0f-4839-9cdd-068b563daa72' -Force } else { throw $_ } } ;"
Java 11.0.22.7.1 was downloaded
Setting Java 11.0.22.7.1 as the default
Malware scan is: disabled
C:\Windows\system32\cmd.exe -/c D:\a\civitai-link-desktop\civitai-link-desktop\codesign\CodeSignTool-v1.3.0\CodeSignTool.bat sign -username=*** -*** -input_file_path=D:\a\civitai-link-desktop\civitai-link-desktop\dist\civitai-link-1.[10](https://github.com/civitai/civitai-link-desktop/actions/runs/8301240635/job/22720926021#step:9:10).6-setup.exe -output_dir_path=D:\a\civitai-link-desktop\civitai-link-desktop\dist\ -malware_block=false
The system cannot find the file specified.
Error: The process 'C:\Windows\system[32](https://github.com/civitai/civitai-link-desktop/actions/runs/8301240635/job/22720926021#step:9:33)\cmd.exe' failed with exit code 1
```

I even added a step before to list on files in the directory. I saw all of the built Windows files but still get `The system cannot find the file specified.`

**Comment by cmoody** [comment]
The docs made it seem like `totp_secret` was not needed unless doing an EV Code Signing. I am using the regular Code Signing certificate but have gone ahead and added `totp_secret`. Still the same results. 

```
C:\Windows\system32\cmd.exe -/c D:\a\civitai-link-desktop\civitai-link-desktop\codesign\CodeSignTool-v1.3.0\CodeSignTool.bat sign -username=*** -*** -totp_secret=*** -input_file_path=D:\a\civitai-link-desktop\civitai-link-desktop\dist\civitai-link-1.10.19-setup.exe -output_dir_path=D:\a\civitai-link-desktop\civitai-link-desktop\dist -malware_block=false
The system cannot find the file specified.
```

**Comment by bayrakmustafa** [comment]
@cmoody I think there is a case that escaped from the tests I wrote while preparing the github action. It may be related to path lengths or some characters. I will do extra tests and get back to you.

**Comment by ssube** [comment]
Could the version of the JDK be the problem?

```
if defined code_sign_tool_path (
%code_sign_tool_path%\jdk-11.0.2\bin\java -Xmx1024M -jar %code_sign_tool_path%\jar\code_sign_tool-1.3.0.jar %*
) else (
.\jdk-11.0.2\bin\java -Xmx1024M -jar .\jar\code_sign_tool-1.3.0.jar %*
)
Shell Cmd: cmd.exe -/c
Exec Cmd : D:\a\civitai-link-desktop\civitai-link-desktop\codesign\CodeSignTool-v1.3.0\CodeSignTool.bat
CodeSigner Command: cmd.exe -/c D:\a\civitai-link-desktop\civitai-link-desktop\codesign\CodeSignTool-v1.3.0\CodeSignTool.bat sign -username="***" -password="***" -totp_secret="" -input_file_path="D:\a\civitai-link-desktop\civitai-link-desktop\dist\civitai-link-1.10.24-setup.exe" -output_dir_path=D:\a\civitai-link-desktop\civitai-link-desktop\dist -malware_block=false
JDK home: C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\8.0.402-6\x64
JDK version: 0
Trying to resolve the latest version from remote
::group::Print information about available versions
Print information about available versions
  corretto-retrieve-available-versions: 37.906ms
  Available versions: [10]
  8: 8.402.08.1, 11: 11.0.22.7.1, 15: 15.0.2.7.1, 16: 16.0.2.7.1, 17: 17.0.10.7.1, 18: 18.0.2.9.1, 19: 19.0.2.7.1, 20: 20.0.2.10.1, 21: 21.0.2.13.1, 22: 22.0.0.36.2
  ::endgroup::
Resolved latest version as 11.0.22.7.1
Trying to download...
Downloading Java 11.0.22.7.1 (Corretto) from https://corretto.aws/downloads/resources/11.0.22.7.1/amazon-corretto-11.0.22.7.1-windows-x64-jdk.zip ...
##[debug]Downloading https://corretto.aws/downloads/resources/11.0.22.7.1/amazon-corretto-11.0.22.7.1-windows-x64-jdk.zip
##[debug]Destination D:\a\_temp\12324f4e-2a94-4c66-9e47-cb73fd0d4ec2
##[debug]download complete
Extracting Java archive...
##[debug]Using pwsh at path: C:\Program Files\PowerShell\7\pwsh.exe
"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.ZipFile } catch { } ; try { [System.IO.Compression.ZipFile]::ExtractToDirectory('D:\a\_temp\12324f4e-2a94-4c66-9e47-cb73fd0d4ec2', 'D:\a\_temp\1a4b8233-1ac8-460a-af5f-a7d4993e2cf1', $true) } catch { if (($_.Exception.GetType().FullName -eq 'System.Management.Automation.MethodException') -or ($_.Exception.GetType().FullName -eq 'System.Management.Automation.RuntimeException') ){ Expand-Archive -LiteralPath 'D:\a\_temp\12324f4e-2a94-4c66-9e47-cb73fd0d4ec2' -DestinationPath 'D:\a\_temp\1a4b8233-1ac8-460a-af5f-a7d4993e2cf1' -Force } else { throw $_ } } ;"
##[debug]Caching tool Java_Corretto_jdk 11.0.22.7.1 x64
##[debug]source dir: D:\a\_temp\1a4b8233-1ac8-460a-af5f-a7d4993e2cf1\jdk11.0.22_7
##[debug]destination C:\hostedtoolcache\windows\Java_Corretto_jdk\11.0.22.7.1\x64
##[debug]finished caching tool
Java 11.0.22.7.1 was downloaded
Setting Java 11.0.22.7.1 as the default
```

Downloading that same JDK locally, I see `/jdk11.0.22_7/bin/`, but the `CodeSignTool.bat` batch script refers to `%code_sign_tool_path%\jdk-11.0.2\bin\java`. It looks like the version is looked up dynamically, so that may have been updated recently?

**Comment by bayrakmustafa** [comment]
@cmoody I could not reproduce the problem you experienced. However, I made an update to a part that might cause the problem. Can you try signing again with the latest version in the develop branch?

**Comment by cmoody** [comment]
I added debug logging to see if that gives us a little more insight. Ultimately looks like the same issue.

```
OAUTH2_ENDPOINT=https://login.ssl.com/oauth2/token
CSC_API_ENDPOINT=https://cs.ssl.com/
TSA_URL=http://ts.ssl.com/
TSA_LEGACY_URL=http://ts.ssl.com/legacy to D:\a\civitai-link-desktop\civitai-link-desktop\codesign\CodeSignTool-v1.3.0\conf\code_sign_tool.properties
Set CODE_SIGN_TOOL_PATH env variable: D:\a\civitai-link-desktop\civitai-link-desktop\codesign\CodeSignTool-v1.3.0
Exec Cmd Content: @echo OFF
set code_sign_tool_path=D:\a\civitai-link-desktop\civitai-link-desktop\codesign\CodeSignTool-v1.3.0
if defined code_sign_tool_path (
%code_sign_tool_path%\jdk-11.0.2\bin\java -Xmx1024M -jar %code_sign_tool_path%\jar\code_sign_tool-1.3.0.jar %*
) else (
.\jdk-11.0.2\bin\java -Xmx1024M -jar .\jar\code_sign_tool-1.3.0.jar %*
)
Shell Cmd: cmd.exe -/c
Exec Cmd : D:\a\civitai-link-desktop\civitai-link-desktop\codesign\CodeSignTool-v1.3.0\CodeSignTool.bat
CodeSigner Command: cmd.exe -/c D:\a\civitai-link-desktop\civitai-link-desktop\codesign\CodeSignTool-v1.3.0\CodeSignTool.bat sign -username="***" -password="***" -totp_secret=*** -input_file_path="D:\a\civitai-link-desktop\civitai-link-desktop\dist\civitai-link-1.10.27-setup.exe" -output_dir_path=D:\a\civitai-link-desktop\civitai-link-desktop\dist -malware_block=false
JDK home: C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\8.0.402-6\x64
JDK version: 0
Trying to resolve the latest version from remote
::group::Print information about available versions
Print information about available versions
Resolved latest version as 11.0.22.7.1
Trying to download...
Downloading Java 11.0.22.7.1 (Corretto) from https://corretto.aws/downloads/resources/11.0.22.7.1/amazon-corretto-11.0.22.7.1-windows-x64-jdk.zip ...
##[debug]Downloading https://corretto.aws/downloads/resources/11.0.22.7.1/amazon-corretto-11.0.22.7.1-windows-x64-jdk.zip
##[debug]Destination D:\a\_temp\ea0028e4-9714-4dff-a0a1-9bc0cc8fb64f
##[debug]download complete
Extracting Java archive...
##[debug]Using pwsh at path: C:\Program Files\PowerShell\7\pwsh.exe
"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.ZipFile } catch { } ; try { [System.IO.Compression.ZipFile]::ExtractToDirectory('D:\a\_temp\ea0028e4-9714-4dff-a0a1-9bc0cc8fb64f', 'D:\a\_temp\80f4c81e-d646-4ff6-90e7-8796e9ffe474', $true) } catch { if (($_.Exception.GetType().FullName -eq 'System.Management.Automation.MethodException') -or ($_.Exception.GetType().FullName -eq 'System.Management.Automation.RuntimeException') ){ Expand-Archive -LiteralPath 'D:\a\_temp\ea0028e4-9714-4dff-a0a1-9bc0cc8fb64f' -DestinationPath 'D:\a\_temp\80f4c81e-d646-4ff6-90e7-8796e9ffe474' -Force } else { throw $_ } } ;"
##[debug]Caching tool Java_Corretto_jdk 11.0.22.7.1 x64
##[debug]source dir: D:\a\_temp\80f4c81e-d646-4ff6-90e7-8796e9ffe474\jdk11.0.22_7
##[debug]destination C:\hostedtoolcache\windows\Java_Corretto_jdk\11.0.22.7.1\x64
##[debug]finished caching tool
Java 11.0.22.7.1 was downloaded
Setting Java 11.0.22.7.1 as the default
Malware scan is: disabled
C:\Windows\system32\cmd.exe -/c D:\a\civitai-link-desktop\civitai-link-desktop\codesign\CodeSignTool-v1.3.0\CodeSignTool.bat sign -username=*** -*** -totp_secret=*** -input_file_path=D:\a\civitai-link-desktop\civitai-link-desktop\dist\civitai-link-1.10.27-setup.exe -output_dir_path=D:\a\civitai-link-desktop\civitai-link-desktop\dist -malware_block=false
The system cannot find the file specified.
Error: The process 'C:\Windows\system32\cmd.exe' failed with exit code 1
##[debug]Node Action run completed with exit code 1
##[debug]CODESIGNTOOL_PATH='D:\a\civitai-link-desktop\civitai-link-desktop\codesign\CodeSignTool-v1.3.0'
##[debug]CODE_SIGN_TOOL_PATH='D:\a\civitai-link-desktop\civitai-link-desktop\codesign\CodeSignTool-v1.3.0'
##[debug]JAVA_HOME='C:\hostedtoolcache\windows\Java_Corretto_jdk\11.0.22.7.1\x64'
##[debug]JAVA_HOME_11_X64='C:\hostedtoolcache\windows\Java_Corretto_jdk\11.0.22.7.1\x64'
##[debug]JAVA_VERSION='11'
##[debug]Set output distribution = Corretto
##[debug]Set output path = C:\hostedtoolcache\windows\Java_Corretto_jdk\11.0.22.7.1\x64
##[debug]Set output version = 11.0.22.7.1
##[debug]Finishing: Sign Artifact with CodeSignTool```

**Comment by cmoody** [comment]
@bayrakmustafa when you are running your tests are you setting the Java Version as part of the build? https://www.ssl.com/how-to/cloud-code-signing-integration-with-github-actions/ has an `Install Maven and Java` step that Im wondering if its setting the version for things to use and we are finding the wrong path.

**Comment by bayrakmustafa** [comment]
@cmoody There is a test I wrote at https://github.com/SSLcom/esigner-codesign/blob/develop/.github/workflows/test.yml#L133. Actually, I don't do anything different from you. It comes with Java in Windows setup. There shouldn't be a situation where the signing command cannot find Java because it uses that Java. I will change the signing command. I will update to use the Java I just installed, not the Java in the Windows setup. I will inform you again when the update is done.

**Comment by bayrakmustafa** [comment]
@cmoody I updated a few places where there might be problems. I also added a log for windows. Can you test the latest version in the develop branch by adding the following parameter?

```
signing_method: v2
```

**Comment by cmoody** [comment]
@bayrakmustafa same issue
```
Java 11.0.22.7.1 was downloaded
Setting Java 11.0.22.7.1 as the default
Malware scan is: disabled
C:\Windows\system32\cmd.exe -/c D:\a\civitai-link-desktop\civitai-link-desktop\codesign\CodeSignTool-v1.3.0\CodeSignTool.bat sign -username=*** -*** -totp_secret=*** -input_file_path=D:\a\civitai-link-desktop\civitai-link-desktop\dist\civitai-link-1.10.28-setup.exe -output_dir_path=D:\a\civitai-link-desktop\civitai-link-desktop\dist -malware_block=false
The system cannot find the file specified.
Error: The process 'C:\Windows\system32\cmd.exe' failed with exit code 1
```

`The system cannot find the file specified.` do we know where this error comes from? I see the files in the path when I use `dir ${{ github.workspace }}` I do see you have steps to copy files from the build to the workspace. Wondering if theres some issue around that where the internal paths dont line up. Grasping at straws at the moment.

**Comment by ssube** [comment]
I've been helping @cmoody debug this and even forked the GH action, which has lead me to believe it is one of the arguments with the paths, but I'm not sure which one/why.

Changing the command that gets executed from `CodeSignTool.bat sign -username=...` to `CodeSignTool.bat sign -help` confirmed that the JDK is installed and the batch script can run the JAR successfully:

```
D:\a\civitai-link-desktop\civitai-link-desktop>set code_sign_tool_path=D:\a\civitai-link-desktop\civitai-link-desktop\codesign\CodeSignTool-v1.3.0 

D:\a\civitai-link-desktop\civitai-link-desktop>if defined code_sign_tool_path (
dir D:\a\civitai-link-desktop\civitai-link-desktop\codesign\CodeSignTool-v1.3.0  
 dir D:\a\civitai-link-desktop\civitai-link-desktop\codesign\CodeSignTool-v1.3.0\jdk-11.0.2  
 dir D:\a\civitai-link-desktop\civitai-link-desktop\codesign\CodeSignTool-v1.3.0\jdk-11.0.2\bin  
 D:\a\civitai-link-desktop\civitai-link-desktop\codesign\CodeSignTool-v1.3.0\jdk-11.0.2\bin\java.exe -jar D:\a\civitai-link-desktop\civitai-link-desktop\codesign\CodeSignTool-v1.3.0\jar\code_sign_tool-1.3.0.jar sign -help 
)  else (.\jdk-11.0.2\bin\java.exe -jar .\jar\code_sign_tool-1.3.0.jar sign -help ) 
 Volume in drive D is Temporary Storage
 Volume Serial Number is 204B-68C1

 Directory of D:\a\civitai-link-desktop\civitai-link-desktop\codesign\CodeSignTool-v1.3.0

03/21/2024  06:05 PM    <DIR>          .
03/21/2024  06:05 PM    <DIR>          ..
03/21/2024  06:05 PM               415 CodeSignTool.bat
03/21/2024  06:05 PM    <DIR>          conf
03/21/2024  06:05 PM    <DIR>          jar
03/21/2024  06:05 PM    <DIR>          jdk-11.0.2
03/21/2024  06:05 PM    <DIR>          logs
06/13/2023  09:01 PM             1,021 release-notes.txt
               2 File(s)          1,436 bytes
               6 Dir(s)  76,146,909,184 bytes free
 Volume in drive D is Temporary Storage
 Volume Serial Number is 204B-68C1
```
and
```
Usage: CodeSignTool sign [-hV] [-malware_block] [-override]
                         [-credential_id=<credentialId>]
                         -input_file_path=<inputFilePath>
                         [-output_dir_path=<outputDirPath>]
                         -*** [-program_name=<programName>]
                         [-totp_secret=<totpSecret>] -username=<username>
Sign code
      -credential_id=<credentialId>
                             Credential ID
  -h, --help                 Show this help message and exit.
      -input_file_path=<inputFilePath>
                             Path of the code object to be signed
      -malware_block         Overrides the malware scan settings configured on
```

Would it be possible for the Java code to print the path that is not found, so that we can confirm it's not an issue with backslashes/quotes being translated incorrectly?

**Comment by ssube** [comment]
I added a check within the JS wrapper to see if the `-input_file_path` exists when that runs, like so:

```
    else if (inputKey == constants_1.INPUT_FILE_PATH) {
        input = path_1.default.normalize(input);
        try {
            const stats = fs.statSync(input);
            console.log('input file path stats:', stats);
        } catch (err) {
            console.error('error checking input file path:', err);
        }
        command = `${command} -input_file_path="${input}"`;
    }
```

and the input file does exist at that point:

```
##[debug]Run CodeSigner
##[debug]Running ESigner.com CodeSign Action ====>
input file path stats: Stats {
  dev: 1348902718,
  mode: 33206,
  nlink: 1,
  uid: 0,
  gid: 0,
  rdev: 0,
  blksize: 4096,
  ino: 562949953425515,
  size: 9563[80](https://github.com/civitai/civitai-link-desktop/actions/runs/8378457401/job/22949113464#step:8:81)74,
  blocks: 1[86](https://github.com/civitai/civitai-link-desktop/actions/runs/8378457401/job/22949113464#step:8:87)800,
  atimeMs: 1711047333007.5652,
  mtimeMs: 1711047333007.5652,
  ctimeMs: 1711047333007.5652,
  birthtimeMs: 1711047329427.4114,
  atime: 2024-03-21T18:55:33.008Z,
  mtime: 2024-03-21T18:55:33.008Z,
  ctime: 2024-03-21T18:55:33.008Z,
  birthtime: 2024-03-21T18:55:29.427Z
}
CodeSignTool output path D:\a\civitai-link-desktop\civitai-link-desktop\dist already exist
```

I was careful to do the `fs.stat` test _after_ the `path_1.default.normalize`, so it should be tested the same path that is provided to the JAR later, but one of them says it exists and the other claims it does not (within the same action, step, etc).

**Comment by cmoody** [comment]
@bayrakmustafa I did try something that was interesting. I copied the creation of that ps1 file and then tried to sign it. Got the same results.
```
name: Build/release Electron app

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: build-linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux

      - name: build-mac
        if: matrix.os == 'macos-latest'
        run: npm run build:mac

      - name: build-win
        if: matrix.os == 'windows-latest'
        run: npm run build:win

      - name: Create Input file for test signing
        shell: bash
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/example
          echo 'Write-Output -InputObject "Happy Signing From ESigner.com!"' > ${GITHUB_WORKSPACE}/example/codesign1.ps1

      - name: Test Signing
        if: matrix.os == 'windows-latest'
        uses: sslcom/esigner-codesign@develop
        with:
          command: sign
          username: ${{ secrets.ES_USERNAME }}
          password: ${{ secrets.ES_PASSWORD }}
          credential_id: ${{ secrets.CREDENTIAL_ID }}
          totp_secret: ${{ secrets.ES_TOTP_SECRET }}
          file_path: ${GITHUB_WORKSPACE}/example/codesign1.ps1
          malware_block: false
          override: true
          environment_name: PROD
          clean_logs: true

      - name: release
        uses: softprops/action-gh-release@v1
        if: always()
        with:
          draft: true
          files: |
            dist/*.exe
            dist/*.zip
            dist/*.dmg
            dist/*.AppImage
            dist/*.snap
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/*.yml
            dist/*.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
```

```
C:\Windows\system32\cmd.exe -/c D:\a\civitai-link-desktop\civitai-link-desktop\codesign\CodeSignTool-v1.3.0\CodeSignTool.bat sign -username=*** -*** -credential_id=*** -totp_secret=*** -input_file_path=D:\a\civitai-link-desktop\civitai-link-desktop\example\codesign1.ps1 -override=true -malware_block=false
The system cannot find the file specified.
Error: The process 'C:\Windows\system32\cmd.exe' failed with exit code 1
```

I thought maybe it was node versions so Ive checked those. Nothing looks too different there. The only thing I changed really was this `environment_name: PROD` instead of it being TEST. Not sure if that impacts any path issues.

Im going to fork the repo tonight and try to see if I can recreate the same failure to help narrow this down.

**Comment by bayrakmustafa** [comment]
@cmoody I tested the yml file you sent by converting it to the figure below, and I still had no problems. There seems to be a very interesting situation. Can you test it with the yml below?

I also made an update to the signing command. Could you try again by adding `signing_method: v2` to your yml file? I completely eliminated the batch file. Signing is done directly via java command. Here is a example: https://github.com/SSLcom/esigner-codesign/blob/develop/.github/workflows/test.yml#L207

```
name: Build/release Electron app

on: [push]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Create Input file for test signing
        shell: bash
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/example
          echo 'Write-Output -InputObject "Happy Signing From ESigner.com!"' > ${GITHUB_WORKSPACE}/example/codesign1.ps1

      - name: Test Signing
        if: matrix.os == 'windows-latest'
        uses: sslcom/esigner-codesign@develop
        with:
          command: sign
          username: ${{ secrets.ES_USERNAME }}
          password: ${{ secrets.ES_PASSWORD }}
          credential_id: ${{ secrets.CREDENTIAL_ID }}
          totp_secret: ${{ secrets.ES_TOTP_SECRET }}
          file_path: ${GITHUB_WORKSPACE}/example/codesign1.ps1
          malware_block: false
          override: true
          environment_name: PROD
          clean_logs: true
```
