### ISSUE TITLE
batch_sign doesn't work if the file has a space in the filename

### ISSUE THREAD

**Issue by Megamannen** [SSLcom/esigner-codesign#22]
Just place a file with space in artifcats/unsigned

(running in a windows-latest runner)

```yaml
- name: Sign Artifact with CodeSignTool
        uses: sslcom/esigner-codesign@v1.3.0
        with:
          command: batch_sign
          username: ${{ secrets.ES_USERNAME }}
          password: ${{ secrets.ES_PASSWORD }}
          credential_id: ${{ secrets.ES_CREDENTIAL_ID }}
          totp_secret: ${{ secrets.ES_TOTP_SECRET }}
          dir_path: ${{ github.workspace }}/artifacts/unsigned
          output_path: ${{ github.workspace }}/artifacts/signed
          malware_block: true
          environment_name: PROD
          ```
