### ISSUE TITLE
Redir URI invalid

### ISSUE THREAD

**Issue by dennisofficial** [SSLcom/esigner-codesign#28]
I've ran this codesigntool locally with the same arguments, and everything works fine, however in the GH Actions, it keeps giving me this error:

`Error: The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.`

```yaml
- name: Sign Artifact with CodeSignTool
  uses: sslcom/esigner-codesign@develop
  with:
    # Sign and timestamp code object.
    command: sign
    # SSL.com account username
    username: ${{ secrets.SSL_ES_PASSWORD }}
    # SSL.com account password.
    password: ${{ secrets.SSL_ES_USERNAME }}
    # Credential ID for signing certificate.
    credential_id: ${{ secrets.SSL_CREDENTIAL_ID }}
    # OAuth TOTP Secret (https://www.ssl.com/how-to/automate-esigner-ev-code-signing)
    totp_secret: ${{ secrets.SSL_ES_TOTP_SECRET }}
    # Path of code object to be signed. (DLL, JAR, EXE, MSI files vb... )
    file_path: ${GITHUB_WORKSPACE}/electron/out/make/squirrel.windows/x64/setup.exe
    # Directory where signed code object(s) will be written.
    output_path: ${GITHUB_WORKSPACE}/artifacts
    # Scan code before sign
    malware_block: false
    # Environment Name, For Production 'PROD' or For Staging 'TEST'
    environment_name: PROD
```
