### ISSUE TITLE
Corrupted jar error when signing a EXE

### ISSUE THREAD

**Issue by rknj** [SSLcom/esigner-codesign#30]
Hello.

We're having issues with the CodeSignTool shell script and I discovered this useful Github action so I'm trying to use it instead to see if it solves our issue.
Unfortunately I'm still getting the same "Corrupt jarfile" error after getting the Windows popup indicating the EXE is well signed.
<img src="https://github.com/user-attachments/assets/ff0b9cb4-8401-4afd-9eb7-cd4c295507c4" alt="corrupt_jarfile" width="300"/>

I don't know what to do next...

Here's the action parameters
```
      - name: Sign Artifact with CodeSignTool
        uses: sslcom/esigner-codesign@develop
        with:
          command: sign
          credential_id: ${{ secrets.CREDENTIAL_ID }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          totp_secret: ${{ secrets.TOTP }}
          file_path: /tmp/artifacts/${{ env.ARTIFACT_NAME }}
          output_path: /tmp/artifacts/signed/
          environment_name: PROD
          jvm_max_memory: 1024M
          signing_method: v2
```
Note that I've tried with both v1 and v2 (I don't know the differences)
